### ISSUE TITLE
☑️ [Task List] - Deployment policy

### ISSUE THREAD

**Issue by wisbech** [project-origin/registry#82]
### Start Date

07/02/2023

## Deployment Policy

In order to deliver a deployment of the Project Origin Registry we need to clarify how we will tackle the following challenges:

### To Do

- [ ] What are the rules of deployment
- [ ] How will we log interactions with the registry
- [ ] How will we do network segmentation
- [ ] etc

### Comments/Unresolved questions

We would love input and expand on these policies from the implementation team from @duizer, @ckr123 etc. I know that @guidmaster is excellent at asking the right questions in this regard.

**Comment by MartinSchmidt** [comment]
This has more to do with the governance around hosting of a setup, and not something to do with the registry implementation
